### ISSUE TITLE
I'm a student now focusing on anomaly detection, is the code you trained based on the library anomalib? If yes, can you share a copy of the code? If yes, can you share a copy of the code with me?

### ISSUE THREAD

**Issue by shjhuangqin** [B1SH0PP/EfficientAD_TRT#5]

**Comment by B1SH0PP** [comment]
@shjhuangqin 
The python code I used is from this biglao: <u>rximg/EfficientAD</u>

**Comment by shjhuangqin** [comment]
May I ask how you packaged it in onnx format? How did you package the three models which are teacher student and ae into one? I'm having trouble exporting the onnx format. Can you share all your python code? My email is 1980696472@qq.com I would appreciate it.  biglao
